version: "3"

services:
    db:
        restart: always
        image: postgres:9.4
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo_db_data:/var/lib/postgresql/data

    odoo:
      restart: always
      image: odoo:11.0
      depends_on:
        - db
      ports:
        - "8069:8069"
      volumes:
          - odoo_web_data:/var/lib/odoo

volumes:
  odoo_db_data:
  odoo_web_data:
